### ISSUE TITLE
absence of ../hash/mameROMs.xml.gz causing NPEs (I think).

### ISSUE THREAD

**Issue by ghost** [MisterTea/MAMEHub#3]
hi, 

having this problem on both Raspbian (ARM6) and Debian (x86_64).

after submitting MAMEhub creds at login screen, getting an error dialog reading: 

```
An exception has occured and has been logged. Returning to login screen
```

in ErrorLog.txt is the message:

```
java.io.FileNotFoundException: ../hash/mameROMs.xml.gz (No such file or directory)
com.mamehub.client.audit.GameAuditor.audit(GameAuditor.java:222)
com.mamehub.client.audit.GameAuditor.run(GameAuditor.java:105)
java.lang.Thread.run(Thread.java:679)
```

And, the exception as seen from the terminal (on Debian/x86_64):

```
[19:59:15,543  INFO RpcEngine.java:397] executing login request 
SERVER RECEIVED: this is a test
SERVER RECEIVED: this is a test
SERVER RECEIVED: this is a test
SERVER RECEIVED: this is a test
SERVER RECEIVED: this is a test
SERVER RECEIVED: this is a test
SERVER RECEIVED: this is a test
SERVER RECEIVED: this is a test
SERVER RECEIVED: this is a test
SERVER RECEIVED: this is a test
[19:59:15,979  INFO UDPReflectionServer.java:68] Shutting down
[19:59:17,679  INFO UDPReflectionServer.java:54] Server shutting down
jar:file:/home/mprov/Bombing_Ground/mamehub/MAMEHub/Client/target/MAMEHubClient-0.0.1-SNAPSHOT.jar!/MAMEHub.png
BUFFERED IMAGE: 248 248
[19:59:18,767  INFO MainFrame.java:392] Adding mainframe window
[19:59:18,785  INFO MainFrame.java:1329] UPDATED WITH 0 (0) VALUES
CHAT STATUS CHANGED: ONLINE
[19:59:19,042  INFO PortOpener.java:89] Remote device updated: D-Link Corporation DNS-343 103
[19:59:19,043  INFO PortOpener.java:89] Remote device updated: D-Link Corporation DNS-343 103
[19:59:19,043  INFO PortOpener.java:89] Remote device updated: D-Link Corporation DNS-343 103
[19:59:19,043  INFO PortOpener.java:89] Remote device updated: D-Link Corporation DNS-343 103
[19:59:19,043  INFO PortOpener.java:89] Remote device updated: D-Link Corporation DNS-343 103
May 8, 2013 7:59:20 PM com.mamehub.client.utility.ClientDatabaseEngine <init>
INFO: CREATING NEW DATABASE ENGINE
May 8, 2013 7:59:20 PM com.mamehub.client.utility.ClientDatabaseEngine <init>
INFO:  db dir: .//MAMEHubAuditDB6 db file.//MAMEHubAuditDB6/db
[19:59:20,939  INFO HashScanner.java:220] Cleaing old reverse-map
[19:59:20,996  INFO HashScanner.java:291] Starting scan..
[19:59:20,997  INFO HashScanner.java:300] Finished reading file headers.
[19:59:20,997  INFO HashScanner.java:319] Finished scanning
[19:59:20,997  INFO HashScanner.java:322] Committed all changes
[19:59:20,997  INFO GameAuditor.java:175] Parsing MAME roms
May 8, 2013 7:59:21 PM com.mamehub.client.utility.ClientDatabaseEngine wipeDatabase
INFO: WIPING OLD DATABASE
May 8, 2013 7:59:21 PM com.mamehub.client.utility.ClientDatabaseEngine wipeDatabase
INFO: ./MAMEHubAuditDB6/db.t
May 8, 2013 7:59:21 PM com.mamehub.client.utility.ClientDatabaseEngine wipeDatabase
INFO: ./MAMEHubAuditDB6/db.d.0
May 8, 2013 7:59:21 PM com.mamehub.client.utility.ClientDatabaseEngine wipeDatabase
INFO: ./MAMEHubAuditDB6/db.i.0
java.io.IOException: java.io.FileNotFoundException: ../hash/mameROMs.xml.gz (No such file or directory)
at com.mamehub.client.audit.GameAuditor.audit(GameAuditor.java:222)
at com.mamehub.client.audit.GameAuditor.run(GameAuditor.java:105)
at java.lang.Thread.run(Thread.java:679)
Caused by: java.io.FileNotFoundException: ../hash/mameROMs.xml.gz (No such file or directory)
at java.io.FileInputStream.open(Native Method)
at java.io.FileInputStream.<init>(FileInputStream.java:137)
at java.io.FileInputStream.<init>(FileInputStream.java:96)
at com.mamehub.client.audit.RomParser.process(RomParser.java:74)
at com.mamehub.client.audit.GameAuditor.audit(GameAuditor.java:176)
... 2 more
java.lang.NullPointerException
at com.mamehub.client.utility.ClientDatabaseEngine.getOrCreateHashMap(ClientDatabaseEngine.java:197)
at com.mamehub.client.audit.GameAuditor.getMameRomInfoMap(GameAuditor.java:331)
at com.mamehub.client.MameHubEngine.getMameRomInfo(MameHubEngine.java:231)
at com.mamehub.client.MainFrame.getGameDescription(MainFrame.java:1335)
at com.mamehub.client.MainFrame.updateJoinGameList(MainFrame.java:1312)
at com.mamehub.client.MainFrame.<init>(MainFrame.java:922)
at com.mamehub.client.login.LoginDialog.loginComplete(LoginDialog.java:374)
at com.mamehub.client.login.LoginDialog$6.actionPerformed(LoginDialog.java:305)
at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2012)
at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2335)
at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:404)
at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
at java.awt.Component.processMouseEvent(Component.java:6288)
at javax.swing.JComponent.processMouseEvent(JComponent.java:3267)
at java.awt.Component.processEvent(Component.java:6053)
at java.awt.Container.processEvent(Container.java:2045)
at java.awt.Component.dispatchEventImpl(Component.java:4649)[19:59:21,221  INFO RpcEngine.java:211] RPC ENGINE TERMINATED
at java.awt.Container.dispatchEventImpl(Container.java:2103)
at java.awt.Component.dispatchEvent(Component.java:4475)
at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4633)
at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4297)
at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4227)
at java.awt.Container.dispatchEventImpl(Container.java:2089)
at java.awt.Window.dispatchEventImpl(Window.java:2587)
at java.awt.Component.dispatchEvent(Component.java:4475)
at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:675)
at java.awt.EventQueue.access$300(EventQueue.java:96)
at java.awt.EventQueue$2.run(EventQueue.java:634)
at java.awt.EventQueue$2.run(EventQueue.java:632)
at java.security.AccessController.doPrivileged(Native Method)
at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:105)
at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:116)
at java.awt.EventQueue$3.run(EventQueue.java:648)
at java.awt.EventQueue$3.run(EventQueue.java:646)
at java.security.AccessController.doPrivileged(Native Method)
at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:105)
at java.awt.EventQueue.dispatchEvent(EventQueue.java:645)
at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:275)
at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:200)
at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:190)
at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:185)
at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:177)
at java.awt.EventDispatchThread.run(EventDispatchThread.java:138)
[19:59:21,348  INFO UDPReflectionServer.java:29] SERVER: Waiting for packet
[19:59:21,348  INFO LoginDialog.java:89] Adding intro dialog
[19:59:23,800  INFO MainFrame.java:400] Removing mainframe window
```

**Comment by jeremyblow** [comment]
So far, I've only worked on mamehub. I'm going to give csmame/mame a go later this evening. I'll let you know how it goes. 

Cool, looking forward it!

JB
