### ISSUE TITLE
update error

### ISSUE THREAD

**Issue by Makushimo** [MisterTea/MAMEHub#309]
Hello, I am trying to enter Mamehub, I get the message down here, my English is very bad, I hope can understand, (use google translator)
Thank you
(edit) I closed the firewall and seems to be working :)

dic 14, 2014 10:33:11 PM com.github.mistertea.updater.ClientDatabaseEngine <init>
INFORMACIËN: CREATING NEW DATABASE ENGINE
dic 14, 2014 10:33:11 PM com.github.mistertea.updater.ClientDatabaseEngine <init>
INFORMACIËN:  db dir: .\UpdaterDB db file.\UpdaterDB/db
Updating MAMEHub, please be patient!!!
Working Directory: C:\Maximo\Juegos\Arcade\MAMEHub\.
Connected to 10ghost.net
Fetching directories...
/MAMEHubRepo
Error getting updates, please copy the error from the console and file a bug her
e: https://github.com/MisterTea/MAMEHub/issues
java.net.SocketException: Permission denied: recv failed
        at java.net.SocketInputStream.socketRead0(Native Method)
        at java.net.SocketInputStream.read(Unknown Source)
        at java.net.SocketInputStream.read(Unknown Source)
        at sun.nio.cs.StreamDecoder.readBytes(Unknown Source)
        at sun.nio.cs.StreamDecoder.implRead(Unknown Source)
        at sun.nio.cs.StreamDecoder.read(Unknown Source)
        at java.io.InputStreamReader.read(Unknown Source)
        at java.io.BufferedReader.fill(Unknown Source)
        at java.io.BufferedReader.read(Unknown Source)
        at org.apache.commons.net.io.CRLFLineReader.readLine(CRLFLineReader.java:58)
        at org.apache.commons.net.ftp.FTP.__getReply(FTP.java:314)
        at org.apache.commons.net.ftp.FTP.__getReply(FTP.java:294)
        at org.apache.commons.net.ftp.FTP.sendCommand(FTP.java:483)
        at org.apache.commons.net.ftp.FTP.sendCommand(FTP.java:608)
        at org.apache.commons.net.ftp.FTP.sendCommand(FTP.java:582)
        at org.apache.commons.net.ftp.FTP.pasv(FTP.java:1007)
        at org.apache.commons.net.ftp.FTPClient._openDataConnection_(FTPClient.java:869)
        at org.apache.commons.net.ftp.FTPClient._openDataConnection_(FTPClient.java:759)
        at org.apache.commons.net.ftp.FTPClient.initiateListParsing(FTPClient.java:3293)
        at org.apache.commons.net.ftp.FTPClient.initiateListParsing(FTPClient.java:3271)
        at org.apache.commons.net.ftp.FTPClient.listFiles(FTPClient.java:2930)
        at com.github.mistertea.updater.Updater.main(Updater.java:161)

**Comment by SaronGas** [comment]
Hey MisterTea I'm having this same issue with o firewall running at all, disabled my virus protection and have windows firewall turned off. I did some looking around and some places say stuff about java and windows 7 having a problem. Told me to delete java and re-run the program and install java when it pops up but that didnt work either. Any Ideas? Its the exact same error the OP posted.

**Comment by SaronGas** [comment]
Nevermind got it. :)
