### ISSUE TITLE
SocketException during installation (recv permission denied)

### ISSUE THREAD

**Issue by OJFreak** [MisterTea/MAMEHub#353]
Java version is 8 u51. No earlier Java has been installed. Running bat file as administrator. Win7 32.

java.net.SocketException: Permission denied: recv failed
        at java.net.SocketInputStream.socketRead0(Native Method)
        at java.net.SocketInputStream.socketRead(Unknown Source)
        at java.net.SocketInputStream.read(Unknown Source)
        at java.net.SocketInputStream.read(Unknown Source)
        at sun.nio.cs.StreamDecoder.readBytes(Unknown Source)
        at sun.nio.cs.StreamDecoder.implRead(Unknown Source)
        at sun.nio.cs.StreamDecoder.read(Unknown Source)
        at java.io.InputStreamReader.read(Unknown Source)
        at java.io.BufferedReader.fill(Unknown Source)
        at java.io.BufferedReader.read(Unknown Source)
        at org.apache.commons.net.io.CRLFLineReader.readLine(CRLFLineReader.java:58)
        at org.apache.commons.net.ftp.FTP.__getReply(FTP.java:314)
        at org.apache.commons.net.ftp.FTP.__getReply(FTP.java:294)
        at org.apache.commons.net.ftp.FTP.sendCommand(FTP.java:483)
        at org.apache.commons.net.ftp.FTP.sendCommand(FTP.java:608)
        at org.apache.commons.net.ftp.FTP.sendCommand(FTP.java:582)
        at org.apache.commons.net.ftp.FTP.pasv(FTP.java:1007)
        at org.apache.commons.net.ftp.FTPClient._openDataConnection_(FTPClient.java:869)
        at org.apache.commons.net.ftp.FTPClient._openDataConnection_(FTPClient.java:759)
        at org.apache.commons.net.ftp.FTPClient.initiateListParsing(FTPClient.java:3293)
        at org.apache.commons.net.ftp.FTPClient.initiateListParsing(FTPClient.java:3271)
        at org.apache.commons.net.ftp.FTPClient.listFiles(FTPClient.java:2930)
        at com.github.mistertea.updater.Updater.main(Updater.java:161)

**Comment by Gitweazle** [comment]
There is a similar report [HERE](https://github.com/MisterTea/MAMEHub/issues/280)

Check your firewall.

Secondly, the latest version of MAMEHub (0.160) does not support 32bit OS. However you can replace the emulator (CSUME.exe) with the previous version (0.154).

**Comment by Prinygod** [comment]
cat you can link issues by mearly doing this #280
